### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cguetot** [COL-IU/msCRUSH#1]
Hi,

I read the msCRUSH paper and I am interested in using this software. So, I downloaded and compile the code, according to the instructions.  However, when I run the `generate_consensus_spectrum_for_mscrush`, I got a  `Segmentation fault (core dumped)`.

I am using Ubuntu 18.04.

best, 

Carlos

**Comment by leiwang-me** [comment]
Hi Carlos,

Thanks for giving msCRUSH a try!  In order to better assist you, could you please update the full command you used for `clustering` and `generating consensus` purposes, respectively?  Based solely on  `Segmentation fault (core dumped)`, we cannot troubleshoot the problem quickly

**Comment by cguetot** [comment]
```
Singularity mscrush:~/projects/emma/new/mscrush/01> generate_consensus_spectrum_for_mscrush D01CS ./mgf/D01 ./mgf/clusters-c*.txt
Loading spectra takes sec:      1.3778e-05
#read spectra: 0
Generating CS for cluster file: [1/5]
file name:      ./mgf/clusters-c0.txt
0 clustering done.
Generating CS for cluster file: [2/5]
file name:      ./mgf/clusters-c2.txt
Segmentation fault (core dumped)
```

**Comment by cguetot** [comment]
It seems like I didn't add the last parameter (mgf files path).  
My mistake!

I will continue testing mscrush.

tack!

**Comment by cguetot** [comment]
Now it ran, but I noted that all floats are reported with 3 digits.  how can I increase it to 7 digits?
thanks again

**Comment by leiwang-me** [comment]
Hi @cguetot , thanks for letting us know that msCRUSH is working for your case. We are making the following changes to msCRUSH, to fulfill your needs.
1. Better command line parser for the inputs. 
2. Provide option/flag to set the output decimal places. 

Thanks for your patience and we should release the new version very soon!

**Comment by leiwang-me** [comment]
Hi @cguetot , thanks very much for your patience!  We have redesigned the whole command line parser, and now it supports flags.  As for outputting floats with more decimal places, such as from 3 decimals to 7 decimals, please `git pull` msCRUSH, compile and then rerun the command `./generate_consensus_spectrum_for_mscrush` with flag `-d 7`.  We have also updated the README, and you are more than welcome to go through the changes!  Please let me know if I can provide further help.
